
/*------------------------------------------------------------------------
    File        : IDisposable
    Purpose     : Interface for classes that allocates recources that GC can't deallocate automatically
    Syntax      : 
    Description : 
    Author(s)   : Andrw Ni
    Created     : 19.12.2018 22:54:02
    Notes       : 
  ----------------------------------------------------------------------*/

interface Prolint.IDisposable:  
    method public void Dispose(). 
end interface.