
/*------------------------------------------------------------------------
    File        : idisposable
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : niand
    Created     : Wed Dec 19 22:54:02 ALMT 2018
    Notes       : 
  ----------------------------------------------------------------------*/

interface Prolint.IDisposable:  
    method public void Dispose(). 
end interface.