
/*------------------------------------------------------------------------
    File        : lintresult
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : niand
    Created     : Tue Dec 18 14:24:42 ALMT 2018
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM prolint.lintresult :  

    DEFINE ENUM 
        LINT_OK        = 0
        COMPILE_ERROR  = 1
        PARSE_ERROR    = 2
        PROPARSE_ERROR = 3
        UNKNOWN_ERROR  = 4. 

END ENUM.